In [ ]:
# (Optional) input directory path tempat file data berada
import os
os.chdir("/content/drive/MyDrive/Purwadhika/Final Project/Experiment/")

In [ ]:
# Import library yang dibutuhkan
import pandas as pd
import sqlite3
import os

In [ ]:
# Deklarasikan dataframe yang mau disimpan dalam bentuk sqlite. Pada contoh ini, dataframe berasal dari read csv. Nantinya bisa diganti dengan dataframe apapun.
df = pd.read_csv("OlistDataset/olist_products_dataset.csv")
df.shape

(32951, 9)

In [ ]:
df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
# Input nama database dan nama table kemudian jalankan code untuk menyimpan table dalam database tersebut.
db_name = 'my_database.db'
table_name = 'products'

conn = sqlite3.connect(db_name)
df.to_sql(table_name, conn, if_exists='replace', index=False)
conn.close()

print(f"Dataframe successfully converted and saved to '{table_name}' table in '{db_name}'.")

# Catatan
# -  Apabila berhasil maka akan terbentuk file db_name.db
# -  Apabila mau menyimpan table lain ke dalam database yang sama, silahkan jalankan code ini lagi dengan nama table yang berbeda.

Dataframe successfully converted and saved to 'products' table in 'my_database.db'.

In [ ]:
# Code ini untuk membuat koneksi dengan database yang ada dan melakukan query SQL
conn = sqlite3.connect(db_name)
query = "SELECT * FROM products"
df_products = pd.read_sql_query(query, conn)
conn.close()

print(f"Displaying the first 5 rows of the '{table_name}' table from '{db_name}':")
display(df_products.head())

Displaying the first 5 rows of the 'products' table from 'my_database.db':

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0